// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package catalogdb

type Artifact struct {
	Name             string `json:"name"`
	CurrentVersionID string `json:"current_version_id"`
}

type PublicationAttempt struct {
	ArtifactName string `json:"artifact_name"`
	Token        string `json:"token"`
	Generation   int64  `json:"generation"`
}

type PublicationGeneration struct {
	ID             int64 `json:"id"`
	NextGeneration int64 `json:"next_generation"`
}

type Version struct {
	ID           string `json:"id"`
	ArtifactName string `json:"artifact_name"`
	PublishedAt  string `json:"published_at"`
	Sequence     int64  `json:"sequence"`
}
