// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package catalogdb

import (
	"context"
)

const deleteArtifactRecord = `-- name: DeleteArtifactRecord :exec
DELETE FROM artifacts WHERE name = ?
`

func (q *Queries) DeleteArtifactRecord(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteArtifactRecord, name)
	return err
}

const deletePublicationAttempt = `-- name: DeletePublicationAttempt :exec
DELETE FROM publication_attempts WHERE artifact_name = ?
`

func (q *Queries) DeletePublicationAttempt(ctx context.Context, artifactName string) error {
	_, err := q.db.ExecContext(ctx, deletePublicationAttempt, artifactName)
	return err
}

const deletePublicationAttemptToken = `-- name: DeletePublicationAttemptToken :exec
DELETE FROM publication_attempts WHERE artifact_name = ? AND token = ?
`

type DeletePublicationAttemptTokenParams struct {
	ArtifactName string `json:"artifact_name"`
	Token        string `json:"token"`
}

func (q *Queries) DeletePublicationAttemptToken(ctx context.Context, arg DeletePublicationAttemptTokenParams) error {
	_, err := q.db.ExecContext(ctx, deletePublicationAttemptToken, arg.ArtifactName, arg.Token)
	return err
}

const deleteVersionRecord = `-- name: DeleteVersionRecord :exec
DELETE FROM versions WHERE artifact_name = ? AND id = ?
`

type DeleteVersionRecordParams struct {
	ArtifactName string `json:"artifact_name"`
	ID           string `json:"id"`
}

func (q *Queries) DeleteVersionRecord(ctx context.Context, arg DeleteVersionRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteVersionRecord, arg.ArtifactName, arg.ID)
	return err
}

const deleteVersionsForArtifact = `-- name: DeleteVersionsForArtifact :exec
DELETE FROM versions WHERE artifact_name = ?
`

func (q *Queries) DeleteVersionsForArtifact(ctx context.Context, artifactName string) error {
	_, err := q.db.ExecContext(ctx, deleteVersionsForArtifact, artifactName)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT a.name, a.current_version_id, v.published_at
FROM artifacts AS a
JOIN versions AS v
  ON v.artifact_name = a.name
 AND v.id = a.current_version_id
WHERE a.name = ?
`

type GetArtifactRow struct {
	Name             string `json:"name"`
	CurrentVersionID string `json:"current_version_id"`
	PublishedAt      string `json:"published_at"`
}

func (q *Queries) GetArtifact(ctx context.Context, name string) (GetArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, name)
	var i GetArtifactRow
	err := row.Scan(&i.Name, &i.CurrentVersionID, &i.PublishedAt)
	return i, err
}

const getEarlierVersion = `-- name: GetEarlierVersion :one
SELECT v.id, v.artifact_name, v.published_at, v.sequence
FROM versions AS v
WHERE v.artifact_name = ?
  AND v.sequence < (
      SELECT current.sequence FROM versions AS current
      WHERE current.artifact_name = ? AND current.id = ?
  )
ORDER BY v.sequence DESC
LIMIT 1
`

type GetEarlierVersionParams struct {
	ArtifactName   string `json:"artifact_name"`
	ArtifactName_2 string `json:"artifact_name_2"`
	ID             string `json:"id"`
}

func (q *Queries) GetEarlierVersion(ctx context.Context, arg GetEarlierVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, getEarlierVersion, arg.ArtifactName, arg.ArtifactName_2, arg.ID)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.ArtifactName,
		&i.PublishedAt,
		&i.Sequence,
	)
	return i, err
}

const getPublicationAttemptToken = `-- name: GetPublicationAttemptToken :one
SELECT token FROM publication_attempts WHERE artifact_name = ?
`

func (q *Queries) GetPublicationAttemptToken(ctx context.Context, artifactName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPublicationAttemptToken, artifactName)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getVersion = `-- name: GetVersion :one
SELECT id, artifact_name, published_at, sequence
FROM versions
WHERE artifact_name = ? AND id = ?
`

type GetVersionParams struct {
	ArtifactName string `json:"artifact_name"`
	ID           string `json:"id"`
}

func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, getVersion, arg.ArtifactName, arg.ID)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.ArtifactName,
		&i.PublishedAt,
		&i.Sequence,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :exec
INSERT INTO artifacts (name, current_version_id)
VALUES (?, ?)
`

type InsertArtifactParams struct {
	Name             string `json:"name"`
	CurrentVersionID string `json:"current_version_id"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertArtifact, arg.Name, arg.CurrentVersionID)
	return err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO versions (id, artifact_name, published_at, sequence)
VALUES (?, ?, ?, ?)
`

type InsertVersionParams struct {
	ID           string `json:"id"`
	ArtifactName string `json:"artifact_name"`
	PublishedAt  string `json:"published_at"`
	Sequence     int64  `json:"sequence"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertVersion,
		arg.ID,
		arg.ArtifactName,
		arg.PublishedAt,
		arg.Sequence,
	)
	return err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT a.name, a.current_version_id, v.published_at
FROM artifacts AS a
JOIN versions AS v
  ON v.artifact_name = a.name
 AND v.id = a.current_version_id
ORDER BY a.name
`

type ListArtifactsRow struct {
	Name             string `json:"name"`
	CurrentVersionID string `json:"current_version_id"`
	PublishedAt      string `json:"published_at"`
}

func (q *Queries) ListArtifacts(ctx context.Context) ([]ListArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsRow{}
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(&i.Name, &i.CurrentVersionID, &i.PublishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservedArtifactNames = `-- name: ListReservedArtifactNames :many
SELECT name FROM artifacts
UNION
SELECT artifact_name AS name FROM publication_attempts
ORDER BY name
`

func (q *Queries) ListReservedArtifactNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listReservedArtifactNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionIDs = `-- name: ListVersionIDs :many
SELECT id FROM versions WHERE artifact_name = ?
`

func (q *Queries) ListVersionIDs(ctx context.Context, artifactName string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listVersionIDs, artifactName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT id, artifact_name, published_at, sequence
FROM versions
WHERE artifact_name = ?
ORDER BY sequence DESC
`

func (q *Queries) ListVersions(ctx context.Context, artifactName string) ([]Version, error) {
	rows, err := q.db.QueryContext(ctx, listVersions, artifactName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Version{}
	for rows.Next() {
		var i Version
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactName,
			&i.PublishedAt,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPublicationGeneration = `-- name: NextPublicationGeneration :one
UPDATE publication_generation
SET next_generation = next_generation + 1
WHERE id = 1
RETURNING next_generation
`

func (q *Queries) NextPublicationGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextPublicationGeneration)
	var next_generation int64
	err := row.Scan(&next_generation)
	return next_generation, err
}

const registerPublicationAttempt = `-- name: RegisterPublicationAttempt :exec
INSERT INTO publication_attempts (artifact_name, token, generation)
VALUES (?, ?, ?)
ON CONFLICT (artifact_name) DO UPDATE
SET token = excluded.token,
    generation = excluded.generation
`

type RegisterPublicationAttemptParams struct {
	ArtifactName string `json:"artifact_name"`
	Token        string `json:"token"`
	Generation   int64  `json:"generation"`
}

func (q *Queries) RegisterPublicationAttempt(ctx context.Context, arg RegisterPublicationAttemptParams) error {
	_, err := q.db.ExecContext(ctx, registerPublicationAttempt, arg.ArtifactName, arg.Token, arg.Generation)
	return err
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE artifacts
SET current_version_id = ?
WHERE name = ?
`

type SetCurrentVersionParams struct {
	CurrentVersionID string `json:"current_version_id"`
	Name             string `json:"name"`
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.ExecContext(ctx, setCurrentVersion, arg.CurrentVersionID, arg.Name)
	return err
}

const upsertArtifact = `-- name: UpsertArtifact :exec
INSERT INTO artifacts (name, current_version_id)
VALUES (?, ?)
ON CONFLICT (name) DO UPDATE SET current_version_id = excluded.current_version_id
`

type UpsertArtifactParams struct {
	Name             string `json:"name"`
	CurrentVersionID string `json:"current_version_id"`
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtifact, arg.Name, arg.CurrentVersionID)
	return err
}
